blank_issues_enabled: true
contact_links:
  - name: "🗪  IRC #neomutt on irc.freenode.net"
    url: https://webchat.freenode.net/#neomutt
    about: Chat with NeoMutt users
  - name: "🖂  Mailing Lists"
    url: https://neomutt.org/#mailing-lists
    about: Discuss NeoMutt with other users and developers
