debian/tmp/usr/bin/neomutt
debian/tmp/usr/share/locale/*

debian/tmp/usr/lib/neomutt/pgpewrap  usr/lib/neomutt/pgpewrap_neomutt
debian/tmp/usr/lib/neomutt/pgpring   usr/lib/neomutt/pgpring_neomutt
debian/tmp/usr/lib/neomutt/smime_keys  usr/lib/neomutt/smime_keys_neomutt

debian/extra/lib/mailspell		    usr/lib/neomutt
debian/extra/lib/source-neomuttrc.d	usr/lib/neomutt
debian/extra/lib/debian-ldap-query	usr/lib/neomutt
debian/extra/lib/mailto-neomutt     usr/lib/neomutt

debian/tmp/neomuttrc		etc
contrib/gpg.rc				etc/neomuttrc.d
contrib/smime.rc			etc/neomuttrc.d
debian/extra/rc/*.rc			etc/neomuttrc.d
debian/extra/neomutt.xpm			usr/share/pixmaps
debian/extra/neomutt.desktop		usr/share/applications
debian/tmp/usr/share/doc/neomutt/*.html	usr/share/doc/neomutt/html
