name: Doxygen
on:
  schedule:
    - cron: '10 3 * * 1'
      # Mondays at 03:10
  push:
    branches:
      - 'doxygen/**'

jobs:
  doxygen:
    name: Update Code Docs
    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Check secret
      run: |
        [ -n "${{ secrets.DOXYGEN_DEPLOY_KEY }}" ]

    - name: Install build software
      run: |
        apt-get update
        apt install -y doxygen graphviz git rsync

    - name: Set up git
      run: |
        git config --global user.email "rich@flatcap.org"
        git config --global user.name "Richard Russon (DEPLOY)"

    - name: Checkout neomutt
      uses: actions/checkout@v2
      with:
        repository: neomutt/neomutt
        path: neomutt
        fetch-depth: 0

    - name: Checkout doxygen scripts
      uses: actions/checkout@v2
      with:
        repository: neomutt/action-doxygen
        path: action-doxygen

    - name: Checkout code docs
      uses: actions/checkout@v2
      with:
        repository: neomutt/code
        path: code
        persist-credentials: false
        # otherwise GITHUB_TOKEN will be used, rather than the Personal Access Token

    - name: Generate docs
      run: |
        cd neomutt
        ln -s ../action-doxygen
        action-doxygen/bin/generate.sh
        ls -l html/index.html

    - name: Commit docs
      run: |
        action-doxygen/bin/commit.sh neomutt/html code

    - name: Push to code docs
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.DOXYGEN_DEPLOY_KEY }}
        branch: main
        directory: code
        repository: neomutt/code

